# Generated by Django 4.2.3 on 2024-02-23 14:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fitness", "0003_rename_puja_name_course_buy_course_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course_buy",
            old_name="course_name",
            new_name="Therpay_name",
        ),
    ]
